# Production environment values
replicaCount: 3

image:
  repository: adamrobbie/soup-and-nutz
  tag: "0.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 4000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: soup-and-nutz.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: soup-and-nutz-tls
      hosts:
        - soup-and-nutz.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

postgresql:
  enabled: true
  auth:
    postgresPassword: ""  # Set via secret
    database: "soup_and_nutz_prod"
  primary:
    persistence:
      enabled: true
      size: 20Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: ""  # Set via secret
  master:
    persistence:
      enabled: true
      size: 5Gi

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: 30

# These should be set via external secrets or environment variables
config:
  secretKeyBase: ""  # Set via secret
  databaseUrl: ""    # Set via secret
  host: "0.0.0.0"
  port: 4000 