apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soup-and-nutz.fullname" . }}-secret
  labels:
    {{- include "soup-and-nutz.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ .Values.config.secretKeyBase | b64enc | quote }}
  database-url: {{ .Values.config.databaseUrl | b64enc | quote }} 